apiVersion: networking.k8s.io/v1 #TEST
kind: Ingress
metadata:
  name: test-ingress
  namespace: octopus
spec:
  ingressClassName: nginx
  rules:
  - host: "octopus.evrgrncloud.com"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: website
              port:
                number: 80
