---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: octopus
    labels:
        app: octopus-underwater-app
spec:
    type: ClusterIP
    selector:
        app: octopus-underwater-app
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000
